#!/usr/bin/env python

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=[
    "src",
    "../crowd_solver"
])

sources = Glob("src/*.cpp")
sources += ["../crowd_solver/crowd_solver_core.cpp"]

library = env.SharedLibrary(
    target="bin/libupheaval_crowd{}{}".format(
        env["suffix"],
        env["SHLIBSUFFIX"]
    ),
    source=sources
)

Default(library)
